### ISSUE TITLE
TypeError: Cannot read property 'nodes' of undefined

### ISSUE THREAD

**Issue by blacksmoke26** [mcollina/avvio#85]
Don't know what kind of error it is. I am using `fastify 2.1.0` not this plugin directly.

```
\node_modules\avvio\time-tree.js:54
  parentNode.nodes.push(childNode)
             ^

TypeError: Cannot read property 'nodes' of undefined
    at TimeTree.add (\node_modules\avvio\time-tree.js:54:14)
    at TimeTree.start (\node_modules\avvio\time-tree.js:60:15)
    at Plugin.obj.once (\node_modules\avvio\boot.js:209:38)
    at Object.onceWrapper (events.js:285:20)
    at Plugin.emit (events.js:197:13)
    at Plugin.exec (\node_modules\avvio\plugin.js:88:8)
    at Boot.loadPlugin (\node_modules\avvio\plugin.js:175:10)
    at release (\node_modules\fastq\queue.js:127:16)
    at Object.resume (\node_modules\fastq\queue.js:61:7)
    at Plugin.finish (\node_modules\avvio\plugin.js:166:10)
    at toLoad.exec (\node_modules\avvio\plugin.js:176:12)
    at done (\node_modules\avvio\plugin.js:115:5)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by mcollina** [comment]
Thanks for reporting! Can you add a way to reproduce your crash? Thanks!

**Comment by blacksmoke26** [comment]
Will do! Thanks!

**Comment by gendronb** [comment]
Same for me...

Either with fastify 2.0.0 or 2.1.0...

Happens when using nested fastify-autoload plugins...

**Comment by mcollina** [comment]
Can you upload a repro on a github repo?

**Comment by gendronb** [comment]
It's a private (client) project, but let me see what I can do... 

Stay tuned...

**Comment by Eomm** [comment]
If it helps I have tried to reproduce like this but it doesn't break:

```
const fastify = require('fastify')()
const AutoLoad = require('fastify-autoload')
const path = require('path')

fastify.register(AutoLoad, {
  dir: path.join(__dirname, 'foo')
})

fastify.listen(3000)

//file: foo/b.js
module.exports = function (fastify, opts, next) {
  // when loaded with autoload, this will be exposed as /something
  fastify.get('/', (request, reply) => {
    reply.send({ hello: 'world' })
  })
}
```

Run also CI in fastify to check if tests are ok, and they are green.

I'll wait for your help to reproduce 🤞

**Comment by gendronb** [comment]
@Eomm did you try to register Autoload inside foo/b.js, to load nested resources?

**Comment by Eomm** [comment]
Yes but it doesn't crash.
I think it is a set of conditions to replicate, not only a plugin configuration.

**Comment by gendronb** [comment]
There you are:  https://github.com/gendronb/fastify-autoload-bug

`yarn start`

```
yarn run v1.12.3
$ fastify start -l info app.js
c:\Data\dev\01-experiments\fastify-autoload-bug\node_modules\avvio\time-tree.js:54
  parentNode.nodes.push(childNode)
             ^

TypeError: Cannot read property 'nodes' of undefined
    at TimeTree.add (c:\Data\dev\01-experiments\fastify-autoload-bug\node_modules\avvio\time-tree.js:54:14)
    at TimeTree.start (c:\Data\dev\01-experiments\fastify-autoload-bug\node_modules\avvio\time-tree.js:60:15)
    at Plugin.obj.once (c:\Data\dev\01-experiments\fastify-autoload-bug\node_modules\avvio\boot.js:209:38)
    at Object.onceWrapper (events.js:277:13)
    at Plugin.emit (events.js:189:13)
    at Plugin.exec (c:\Data\dev\01-experiments\fastify-autoload-bug\node_modules\avvio\plugin.js:88:8)
    at Boot.loadPlugin (c:\Data\dev\01-experiments\fastify-autoload-bug\node_modules\avvio\plugin.js:175:10)
    at Task.release (c:\Data\dev\01-experiments\fastify-autoload-bug\node_modules\fastq\queue.js:127:16)
    at worked (c:\Data\dev\01-experiments\fastify-autoload-bug\node_modules\fastq\queue.js:169:10)
    at toLoad.finish (c:\Data\dev\01-experiments\fastify-autoload-bug\node_modules\avvio\plugin.js:178:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Eomm** [comment]
@blacksmoke26 are you using the `fastify-autoload` also?

I think I found the problem, I need to think about how fix in a good way.

The problem is that some functions are loaded multiple times in a strange nasted way (look for the `C:\Users\behem\workspaceFastify\fastify-autoload-bug\node_modules\fastify-autoload\index.js`)
```
bound root 26 ms
└─┬ C:\Users\behem\workspaceFastify\fastify-autoload-bug\app.js 20 ms
  └─┬ C:\Users\behem\workspaceFastify\fastify-autoload-bug\node_modules\fastify-autoload\index.js 18 ms
    └─┬ C:\Users\behem\workspaceFastify\fastify-autoload-bug\plugins\index.js 2 ms
      └─┬ C:\Users\behem\workspaceFastify\fastify-autoload-bug\node_modules\fastify-autoload\index.js 1 ms
        ├── C:\Users\behem\workspaceFastify\fastify-autoload-bug\plugins\modules\index.js 0 ms
        └── C:\Users\behem\workspaceFastify\fastify-autoload-bug\plugins\modules\index.js 0 ms
```

Thanks for the error replication 💪

**Comment by mcollina** [comment]
The problem is due to the fact that plugins could be loaded multiple times. You might want to differentiate at which level they are loaded.

**Comment by gendronb** [comment]
@mcollina not sure to understand what you mean by "differentiate at which level they are loader",,,

**Comment by mcollina** [comment]
The name algorithm does not generate unique names. The time tracking algorithms require unique names to work. By loading the same module twice, you trigger this bug.

**Comment by blacksmoke26** [comment]
The solution worked for me.

Convert module file(s) (e.g., routes in my case) into fastify plugin then register.

**Comment by blacksmoke26** [comment]
@Eomm nope, I was doing the same as you:

```js
//file: foo/b.js
module.exports = function (fastify, opts, next) {
  // when loaded with autoload, this will be exposed as /something
  fastify.get('/', (request, reply) => {
    reply.send({ hello: 'world' })
  })
}
```
Transform above code into a plugin, your issue will be resolved.

```js
'use strict';

const fp = require('fastify-plugin');

// Export plugin to module
//file: /path/to/routes.js
module.exports = fp(async ( fastify, opts, next ) => {
  // when loaded with autoload, this will be exposed as /something
  fastify.get('/', (request, reply) => {
    reply.send({ hello: 'world' })
  })
}, {
  name: 'fastify-routes',
});


// Somewhere
fastify.register(require('/path/to/routes'));
```

**Comment by mcollina** [comment]
Is this still an issue? I’ve released the fix as avvio 6.2.1.

**Comment by blacksmoke26** [comment]
Not anymore!

**Comment by gendronb** [comment]
@mcollina still not for the code submitted above. ( https://github.com/gendronb/fastify-autoload-bug) avvio is now at version 2.6.1, but I get a different error, looks like the module is loaded more than once (maybe me not using the autoload plugin ccorrectly?) : 

```
yarn run v1.12.3
$ fastify start -l info app.js
assert.js:753
    throw newErr;
    ^

AssertionError [ERR_ASSERTION]: ifError got unwanted exception: Method 'GET' already declared for route '/test'
    at wrap (c:\Data\dev\01-experiments\fastify-autoload-bug\node_modules\fastify-cli\start.js:143:5)
    at ready.err (c:\Data\dev\01-experiments\fastify-autoload-bug\node_modules\fastify\lib\server.js:129:31)
    at Object._encapsulateThreeParam (c:\Data\dev\01-experiments\fastify-autoload-bug\node_modules\avvio\boot.js:410:13)
    at Router._insert (c:\Data\dev\01-experiments\fastify-autoload-bug\node_modules\find-my-way\index.js:275:9)
    at Router._on (c:\Data\dev\01-experiments\fastify-autoload-bug\node_modules\find-my-way\index.js:177:8)
    at Router.on (c:\Data\dev\01-experiments\fastify-autoload-bug\node_modules\find-my-way\index.js:66:8)
    at Object.afterRouteAdded (c:\Data\dev\01-experiments\fastify-autoload-bug\node_modules\fastify\fastify.js:484:16)
    at after (c:\Data\dev\01-experiments\fastify-autoload-bug\node_modules\fastify\fastify.js:405:23)
    at Object._encapsulateThreeParam (c:\Data\dev\01-experiments\fastify-autoload-bug\node_modules\avvio\boot.js:419:7)
    at Boot.callWithCbOrNextTick (c:\Data\dev\01-experiments\fastify-autoload-bug\node_modules\avvio\boot.js:341:5)
    at Boot._after (c:\Data\dev\01-experiments\fastify-autoload-bug\node_modules\avvio\boot.js:232:26)
    at Plugin.exec (c:\Data\dev\01-experiments\fastify-autoload-bug\node_modules\avvio\plugin.js:89:17)
    at Boot.loadPlugin (c:\Data\dev\01-experiments\fastify-autoload-bug\node_modules\avvio\plugin.js:175:10)
error Command failed with exit code 1.
```

**Comment by gendronb** [comment]
If I refer to fastify-autoload documentation (excerpt below), I should not need to transform my code to a plugin (as mentionned by @blacksmoke26)...

```
// index.js
fastify.register(AutoLoad, {
  dir: path.join(__dirname, 'foo'),
  options: { prefix: '/defaultPrefix' }
})

// /foo/something.js
module.exports = function (fastify, opts, next) {
  // your plugin
}
```

**Comment by gendronb** [comment]
Sorry, I see my problem... Forget about my 2 most recent comments, and thanks for you help and great librairies!
